site_name: Asteria
site_url: https://blog.shiwj.com
repo_url: https://github.com/openjz/asteria
copyright: "©2020-2025 shiwj | 津ICP备2020010292号-1"
docs_dir: docs
site_dir: site

theme:
  name: material
  favicon: img/avatar.png
  icon:
    logo: material/star
  features:
    - navigation.tabs
    - navigation.tabs.sticky

# math
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
